variable "project_id" {
  type        = string
  description = "GCPプロジェクトID"
  default     = "compact-system-398013"
}

variable "airbyte_cloud_api_key" {
  type        = string
  description = "Airbyte CloudのAPIキー"
  default     = "eyJhbGciOiJSUzI1NiIsImtpZCI6ImY0YzBlY2FjLTFmMjktNDVkMS05NzJjLTNiNzFlMzY5NDhkNCIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiY2xhazFzdTU5MDAwMDNiNmNqNW1tcWc4dSJdLCJjdXN0b21lcl9pZCI6IjgxNjVlOThhLTE4OTQtNDJjZC04OThmLWQxNWI5OTM0ZGFjYiIsImVtYWlsIjoic2FrdS5zdHVkeXBnQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImV4cCI6MjUzNDAyMjE0NDAwLCJpYXQiOjE2OTM5MjIwNTQsImlzcyI6Imh0dHBzOi8vYXBwLnNwZWFrZWFzeWFwaS5kZXYvdjEvYXV0aC9vYXV0aC9jbGFrMXN1NTkwMDAwM2I2Y2o1bW1xZzh1IiwianRpIjoiZjRjMGVjYWMtMWYyOS00NWQxLTk3MmMtM2I3MWUzNjk0OGQ0Iiwia2lkIjoiZjRjMGVjYWMtMWYyOS00NWQxLTk3MmMtM2I3MWUzNjk0OGQ0IiwibmJmIjoxNjkzOTIxOTk0LCJzcGVha2Vhc3lfY3VzdG9tZXJfaWQiOiJKQThzNll4VEFXaDk2QkRZb1c0a2ZZQjcwUG0xIiwic3BlYWtlYXN5X3dvcmtzcGFjZV9pZCI6ImNsYWsxc3U1OTAwMDAzYjZjajVtbXFnOHUiLCJzdWIiOiJKQThzNll4VEFXaDk2QkRZb1c0a2ZZQjcwUG0xIiwidXNlcl9pZCI6IkpBOHM2WXhUQVdoOTZCRFlvVzRrZllCNzBQbTEifQ.pIkrTkoS8n40tvVHjPVscadEh4MkOLJ2tcPhoeHDB8PfT54cQDXNb4S72iqGsvUM7622ec36jDTkGPaOfmEyXTjuCGxXpyOGryVdL8TcpCZSIpURqYUFBHW_rketZ1I2mlCqIxNEKBuGSU7k3OvWCbxPWWak_-eLMgQix2Dx3OmkrolC7UG7ovgI3qo3tKrhGwDoMK4oOdKasJjy0wS4H4pmU7uOoGA7fqEqYbEXCUt-6Bz-abkSNzM8kMZIFXNjG8Cf9gh5TtKfZifqhL5Bi1VA8f1NlsJ4EiUTqp6VbUdxjrybrV0YWoyCdj7c58OJ9Qf_Ace5M6BRI-U_FVahbg"
}

# variable "credentials_json" {
#   type        = string
#   description = "Google Cloudのアクセスキー(json形式)"
# }
